/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SchedulesRouteImport } from './routes/schedules'
import { Route as FinalsRouteImport } from './routes/finals'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as ProfileScheduleRouteImport } from './routes/profile/schedule'
import { Route as ProfileSavedRouteImport } from './routes/profile/saved'
import { Route as ProfileFriendsRouteImport } from './routes/profile/friends'
import { Route as ProfileCurrentRouteImport } from './routes/profile/current'
import { Route as ProfileCompletedRouteImport } from './routes/profile/completed'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SchedulesRoute = SchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => rootRouteImport,
} as any)
const FinalsRoute = FinalsRouteImport.update({
  id: '/finals',
  path: '/finals',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileScheduleRoute = ProfileScheduleRouteImport.update({
  id: '/profile/schedule',
  path: '/profile/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSavedRoute = ProfileSavedRouteImport.update({
  id: '/profile/saved',
  path: '/profile/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileFriendsRoute = ProfileFriendsRouteImport.update({
  id: '/profile/friends',
  path: '/profile/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileCurrentRoute = ProfileCurrentRouteImport.update({
  id: '/profile/current',
  path: '/profile/current',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileCompletedRoute = ProfileCompletedRouteImport.update({
  id: '/profile/completed',
  path: '/profile/completed',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/finals': typeof FinalsRoute
  '/schedules': typeof SchedulesRoute
  '/search': typeof SearchRoute
  '/profile/completed': typeof ProfileCompletedRoute
  '/profile/current': typeof ProfileCurrentRoute
  '/profile/friends': typeof ProfileFriendsRoute
  '/profile/saved': typeof ProfileSavedRoute
  '/profile/schedule': typeof ProfileScheduleRoute
  '/profile': typeof ProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/finals': typeof FinalsRoute
  '/schedules': typeof SchedulesRoute
  '/search': typeof SearchRoute
  '/profile/completed': typeof ProfileCompletedRoute
  '/profile/current': typeof ProfileCurrentRoute
  '/profile/friends': typeof ProfileFriendsRoute
  '/profile/saved': typeof ProfileSavedRoute
  '/profile/schedule': typeof ProfileScheduleRoute
  '/profile': typeof ProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/finals': typeof FinalsRoute
  '/schedules': typeof SchedulesRoute
  '/search': typeof SearchRoute
  '/profile/completed': typeof ProfileCompletedRoute
  '/profile/current': typeof ProfileCurrentRoute
  '/profile/friends': typeof ProfileFriendsRoute
  '/profile/saved': typeof ProfileSavedRoute
  '/profile/schedule': typeof ProfileScheduleRoute
  '/profile/': typeof ProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/finals'
    | '/schedules'
    | '/search'
    | '/profile/completed'
    | '/profile/current'
    | '/profile/friends'
    | '/profile/saved'
    | '/profile/schedule'
    | '/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/finals'
    | '/schedules'
    | '/search'
    | '/profile/completed'
    | '/profile/current'
    | '/profile/friends'
    | '/profile/saved'
    | '/profile/schedule'
    | '/profile'
  id:
    | '__root__'
    | '/'
    | '/finals'
    | '/schedules'
    | '/search'
    | '/profile/completed'
    | '/profile/current'
    | '/profile/friends'
    | '/profile/saved'
    | '/profile/schedule'
    | '/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FinalsRoute: typeof FinalsRoute
  SchedulesRoute: typeof SchedulesRoute
  SearchRoute: typeof SearchRoute
  ProfileCompletedRoute: typeof ProfileCompletedRoute
  ProfileCurrentRoute: typeof ProfileCurrentRoute
  ProfileFriendsRoute: typeof ProfileFriendsRoute
  ProfileSavedRoute: typeof ProfileSavedRoute
  ProfileScheduleRoute: typeof ProfileScheduleRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedules': {
      id: '/schedules'
      path: '/schedules'
      fullPath: '/schedules'
      preLoaderRoute: typeof SchedulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finals': {
      id: '/finals'
      path: '/finals'
      fullPath: '/finals'
      preLoaderRoute: typeof FinalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/schedule': {
      id: '/profile/schedule'
      path: '/profile/schedule'
      fullPath: '/profile/schedule'
      preLoaderRoute: typeof ProfileScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/saved': {
      id: '/profile/saved'
      path: '/profile/saved'
      fullPath: '/profile/saved'
      preLoaderRoute: typeof ProfileSavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/friends': {
      id: '/profile/friends'
      path: '/profile/friends'
      fullPath: '/profile/friends'
      preLoaderRoute: typeof ProfileFriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/current': {
      id: '/profile/current'
      path: '/profile/current'
      fullPath: '/profile/current'
      preLoaderRoute: typeof ProfileCurrentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/completed': {
      id: '/profile/completed'
      path: '/profile/completed'
      fullPath: '/profile/completed'
      preLoaderRoute: typeof ProfileCompletedRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FinalsRoute: FinalsRoute,
  SchedulesRoute: SchedulesRoute,
  SearchRoute: SearchRoute,
  ProfileCompletedRoute: ProfileCompletedRoute,
  ProfileCurrentRoute: ProfileCurrentRoute,
  ProfileFriendsRoute: ProfileFriendsRoute,
  ProfileSavedRoute: ProfileSavedRoute,
  ProfileScheduleRoute: ProfileScheduleRoute,
  ProfileIndexRoute: ProfileIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
